version: "2"

services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - ./app:/app
    restart: always
    environment:
      SERVICE_NAME: "Email Scheduler App"
      DATABASE_URL: "mysql+aiomysql://local:local123@db:3306/app"
      EMAIL_ADDRESS: "tarasera.tara@gmail.com"
      EMAIL_PASSWORD: "tara123tarasera123"
      APP_HOST: "0.0.0.0"
      APP_PORT: "3000"
      CHECK_INTERVAL: 1
      LOG_LEVEL: "ERROR"
      LOG_DISABLE: "false"
    ports:
      - "3000:3000"
    command: bash -c "./wait-for-it.sh db:3306 && cd ./main && python3 ./main.py"

  db:
    image: mysql:5.7
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      MYSQL_USER: local
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: local123
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"